"""adds condition column to fixed assets table

Revision ID: 0ff65eac702a
Revises: 71a6c9e7cd15
Create Date: 2025-03-27 00:32:16.985501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff65eac702a'
down_revision = '71a6c9e7cd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
