"""adds vendors table

Revision ID: 1a334aa5f696
Revises: 0cbd7e60852d
Create Date: 2025-03-17 14:26:34.592032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a334aa5f696'
down_revision = '0cbd7e60852d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('kra_pin', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('paybill_number', sa.String(length=255), nullable=True),
    sa.Column('till_number', sa.String(length=255), nullable=True),
    sa.Column('contact_person_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person_email', sa.String(length=255), nullable=True),
    sa.Column('contact_person_contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kra_pin'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    # ### end Alembic commands ###
