"""minor fix

Revision ID: 1fa856f110f9
Revises: 6587c4b926a4
Create Date: 2025-04-07 16:42:06.678442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa856f110f9'
down_revision = '6587c4b926a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_history_inventory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_items', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_history_inventory_id_fkey', 'inventories', ['inventory_id'], ['id'])

    # ### end Alembic commands ###
