"""adds spaceId column ti inventory items table

Revision ID: 34469e47f527
Revises: 3d070dcbe180
Create Date: 2025-04-01 21:01:30.947826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34469e47f527'
down_revision = '3d070dcbe180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spaces', ['space_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('space_id')

    # ### end Alembic commands ###
