"""removes location column from fixed assets table

Revision ID: 4d010d20d31e
Revises: b0880fa8d6e5
Create Date: 2025-03-19 17:16:56.632044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d010d20d31e'
down_revision = 'b0880fa8d6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
