"""adds account name column to the vendors table

Revision ID: 68c14c9962e5
Revises: 1a334aa5f696
Create Date: 2025-03-18 12:40:40.764843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c14c9962e5'
down_revision = '1a334aa5f696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
