"""adds status column to request table

Revision ID: 71a6c9e7cd15
Revises: c22e8249efac
Create Date: 2025-03-26 13:36:39.061917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a6c9e7cd15'
down_revision = 'c22e8249efac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
