"""minor fix

Revision ID: 76e228b5619a
Revises: 89bb4ec6af10
Create Date: 2025-03-22 16:21:56.125142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e228b5619a'
down_revision = '89bb4ec6af10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_asset_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spaces', ['space_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_asset_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('space_id')

    # ### end Alembic commands ###
