"""adds unit cost column to InventoryItem table

Revision ID: 776a3000b032
Revises: 67b02108f1b5
Create Date: 2025-03-31 19:40:53.786143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776a3000b032'
down_revision = '67b02108f1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    # ### end Alembic commands ###
