"""adds inventoryhistory table

Revision ID: 843f31c16b37
Revises: 34469e47f527
Create Date: 2025-04-07 16:22:10.645612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f31c16b37'
down_revision = '34469e47f527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_history')
    # ### end Alembic commands ###
