"""adds type columns to history tables

Revision ID: 8c794bebef98
Revises: b76fed0edd76
Create Date: 2025-04-07 17:54:58.863142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c794bebef98'
down_revision = 'b76fed0edd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_asset_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('fixed_asset_history', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
