"""adds inventory and inventory categories tables

Revision ID: 91653de26c9c
Revises: 0ff65eac702a
Create Date: 2025-03-31 19:06:00.258589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91653de26c9c'
down_revision = '0ff65eac702a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
